import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { CheckCircle2, FileText, MapPin, UserRound, UsersRound, Sprout } from "lucide-react";
interface Props { formData: any; updateFormData: (data: any) => void; }
const value=(v:any,empty="Non renseigné")=>v!==undefined&&v!==null&&String(v).trim()!==""?String(v):empty;
const fileName=(f:any)=>f?.name||null;
export const EtapeConfirmationDossier=({formData,updateFormData}:Props)=>{
 const offre=formData.offre||{}; const ha=Number(formData.superficie_prevue||0); const rep=Boolean(formData.has_representant);
 const docs=Object.keys(formData).filter(k=>k.startsWith("doc_")&&k.endsWith("_file")&&formData[k]);
 const contracts=Object.keys(formData).filter(k=>k.startsWith("contrat_")&&k.endsWith("_file")&&formData[k]);
 const location=[formData.district_nom,formData.region_nom,formData.departement_nom,formData.sous_prefecture_nom,formData.village_nom||formData.village_propre].filter(Boolean).join(" / ");
 const clientName=(String(formData.nom_famille||"")+" "+String(formData.prenoms||"")).trim();
 const repName=(String(formData.representant_nom||"")+" "+String(formData.representant_prenoms||"")).trim();
 return <div className="space-y-6">
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5"/>Récapitulatif du dossier</CardTitle></CardHeader><CardContent className="space-y-5">
   <section className="rounded-xl border p-4 space-y-3"><h3 className="font-semibold flex items-center gap-2"><Sprout className="h-4 w-4"/>Offre et projet</h3><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 text-sm"><div><p className="text-xs text-muted-foreground">Offre</p><p className="font-medium">{value(offre.nom||formData.offre_code)}</p></div><div><p className="text-xs text-muted-foreground">Code parcours</p><p>{value(formData.offre_code)}</p></div><div><p className="text-xs text-muted-foreground">Superficie</p><p>{ha>0?ha+" ha":"Non renseignée"}</p></div><div><p className="text-xs text-muted-foreground">Paiement</p><p>{formData.mode_paiement==="comptant"?"Comptant":"Échéancier"}</p></div></div></section>
   <section className="rounded-xl border p-4 space-y-3"><h3 className="font-semibold flex items-center gap-2"><UserRound className="h-4 w-4"/>Informations du client</h3><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 text-sm"><div><p className="text-xs text-muted-foreground">Nom</p><p className="font-medium">{value(clientName)}</p></div><div><p className="text-xs text-muted-foreground">Pièce</p><p>{value(formData.type_piece)} — {value(formData.numero_piece)}</p></div><div><p className="text-xs text-muted-foreground">Téléphone</p><p>{value(formData.telephone)}</p></div><div><p className="text-xs text-muted-foreground">WhatsApp</p><p>{value(formData.whatsapp)}</p></div><div><p className="text-xs text-muted-foreground">Email</p><p>{value(formData.email)}</p></div><div><p className="text-xs text-muted-foreground">Nationalité</p><p>{value(formData.nationalite)}</p></div></div></section>
   <section className="rounded-xl border p-4 space-y-3"><h3 className="font-semibold flex items-center gap-2"><MapPin className="h-4 w-4"/>Résidence / localisation</h3><p className="text-sm">{value(location)}</p><p className="text-sm text-muted-foreground">{value(formData.domicile)}</p></section>
   <section className="rounded-xl border p-4 space-y-3"><h3 className="font-semibold flex items-center gap-2"><UsersRound className="h-4 w-4"/>Cotitulaire / mandataire</h3>{rep?<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 text-sm"><div><p className="text-xs text-muted-foreground">Qualité</p><p>{value(formData.representant_type)}</p></div><div><p className="text-xs text-muted-foreground">Nom</p><p className="font-medium">{value(repName)}</p></div><div><p className="text-xs text-muted-foreground">Lien avec le Client</p><p>{value(formData.representant_lien)}</p></div><div><p className="text-xs text-muted-foreground">Pièce</p><p>{value(formData.representant_type_piece)} — {value(formData.representant_numero_piece)}</p></div><div><p className="text-xs text-muted-foreground">Téléphone</p><p>{value(formData.representant_telephone)}</p></div><div><p className="text-xs text-muted-foreground">WhatsApp</p><p>{value(formData.representant_whatsapp)}</p></div></div>:<p className="text-sm text-muted-foreground">Aucun cotitulaire ou mandataire désigné.</p>}</section>
   <section className="rounded-xl border p-4 space-y-3"><h3 className="font-semibold">Documents et contrats</h3><div className="grid sm:grid-cols-2 gap-2 text-sm"><div className="flex items-center gap-2"><FileText className="h-4 w-4"/>{docs.length} document(s) téléversé(s)</div><div className="flex items-center gap-2"><FileText className="h-4 w-4"/>{contracts.length} contrat(s) téléversé(s)</div></div>{docs.length+contracts.length>0&&<div className="flex flex-wrap gap-2">{[...docs,...contracts].map(k=><Badge key={k} variant="outline">{fileName(formData[k])}</Badge>)}</div>}</section>
  </CardContent></Card>
  <Card><CardHeader><CardTitle>Validation finale</CardTitle></CardHeader><CardContent className="space-y-3">{[
   ["contrat_lu","Le Client a pris connaissance des documents contractuels applicables."],["documents_authentiques","Les documents fournis ont été contrôlés et déclarés authentiques."],["autorisation_donnees","Le Client autorise le traitement de ses données pour l’exécution du dossier."]
  ].map(([id,label])=><div className="flex items-start gap-2" key={id}><Checkbox id={id} checked={Boolean(formData[id])} onCheckedChange={v=>updateFormData({[id]:Boolean(v)})}/><Label htmlFor={id} className="font-normal">{label}</Label></div>)}</CardContent></Card>
 </div>;
};