const esc=(v:any)=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");
const col=(n:number)=>{let s="";for(;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
const xmlCell=(v:any,r:string,style=0)=>{
 if(v===null||v===undefined||v==="")return `<c r="${r}" s="${style}" t="inlineStr"><is><t></t></is></c>`;
 if(typeof v==="number"&&Number.isFinite(v))return `<c r="${r}" s="${style}"><v>${v}</v></c>`;
 return `<c r="${r}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`;
};
const crc32=(bytes:Uint8Array)=>{let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0};
const u16=(n:number)=>[n&255,(n>>>8)&255],u32=(n:number)=>[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255];
const zip=(files:{name:string;data:string}[])=>{
 const enc=new TextEncoder(), chunks:number[]=[]; const central:any[]=[]; let off=0;
 const push=(a:number[])=>chunks.push(...a);
 for(const f of files){const b=enc.encode(f.data),crc=crc32(b),nb=enc.encode(f.name);const head=[0x50,0x4b,3,4,20,0,0,0,0,0,0,0,0,0,...u32(crc),...u32(b.length),...u32(b.length),...u16(nb.length),0,0];push(head);push([...nb]);push([...b]);central.push({nb,crc,size:b.length,off});off+=head.length+nb.length+b.length;}
 const cdStart=off;for(const x of central){push([0x50,0x4b,1,2,20,0,20,0,0,0,0,0,0,0,...u32(x.crc),...u32(x.size),...u32(x.size),...u16(x.nb.length),0,0,0,0,0,0,0,0,0,0,0,0,...u32(x.off)]);push([...x.nb]);}const cdSize=off-cdStart;push([0x50,0x4b,5,6,0,0,0,0,...u16(central.length),...u16(central.length),...u32(cdSize),...u32(cdStart),0,0]);return new Blob([new Uint8Array(chunks)],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});
};
export type Sheet={name:string;rows:any[][];widths?:number[];freeze?:number;autoFilter?:boolean;conditional?:{range:string;formula:string;style:number}[];merges?:string[];moneyCols?:number[];percentCols?:number[]};
export async function exportFinancialWorkbook(sheets:Sheet[],filename:string){
 const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="2"><numFmt numFmtId="164" formatCode="#,##0 &quot;FCFA&quot;"/><numFmt numFmtId="165" formatCode="0.0%"/></numFmts>
<fonts count="3"><font><sz val="10"/><name val="Aptos"/></font><font><b/><sz val="10"/><color rgb="FFFFFFFF"/><name val="Aptos"/></font><font><b/><sz val="16"/><color rgb="FFFFFFFF"/><name val="Aptos Display"/></font></fonts>
<fills count="6"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF0B6B3A"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFD9A441"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE8F3EC"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFF3D8"/></patternFill></fill></fills>
<borders count="2"><border/><border><bottom style="thin"><color rgb="FFB7C8BE"/></bottom></border></borders>
<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>
<cellXfs count="9"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/><xf numFmtId="0" fontId="2" fillId="2" borderId="0" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="1" fillId="3" borderId="0" applyAlignment="1"><alignment horizontal="center"/></xf><xf numFmtId="164" fontId="0" fillId="0" borderId="1"/><xf numFmtId="0" fontId="0" fillId="4" borderId="1"/><xf numFmtId="0" fontId="0" fillId="5" borderId="1"/><xf numFmtId="0" fontId="0" fillId="0" borderId="1" applyAlignment="1"><alignment horizontal="center"/></xf><xf numFmtId="165" fontId="0" fillId="0" borderId="1"/></cellXfs>
<dxfs count="3"><dxf><fill><patternFill patternType="solid"><fgColor rgb="FFC6EFCE"/></patternFill></fill><font><color rgb="FF006100"/></font></dxf><dxf><fill><patternFill patternType="solid"><fgColor rgb="FFFFC7CE"/></patternFill></fill><font><color rgb="FF9C0006"/></font></dxf><dxf><fill><patternFill patternType="solid"><fgColor rgb="FFFFEB9C"/></patternFill></fill><font><color rgb="FF9C6500"/></font></dxf></dxfs></styleSheet>`;
 const contentTypes=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join("")}</Types>`;
 const rels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`;
 const wbRels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join("")}<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;
 const wb=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><bookViews><workbookView activeTab="0"/></bookViews><sheets>${sheets.map((s,i)=>`<sheet name="${esc(s.name.slice(0,31))}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join("")}</sheets></workbook>`;
 const sheetXml=(s:Sheet)=>{
   const rows=s.rows.map((row,ri)=>{const styleFor=(ci:number,v:any)=>ri===0?1:ri===1?2:ri===2?3:(typeof v==="number"&&s.moneyCols?.includes(ci)?4:typeof v==="number"&&s.percentCols?.includes(ci)?8:ci===0?7:0);return `<row r="${ri+1}" ht="${ri===0?28:ri===1?22:ri===2?22:19}" customHeight="1">${row.map((v,ci)=>xmlCell(v,`${col(ci+1)}${ri+1}`,styleFor(ci,v))).join("")}</row>`}).join("");
   const cols=(s.widths||[]).map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join("");
   const cf=(s.conditional||[]).map((x,i)=>`<conditionalFormatting sqref="${x.range}"><cfRule type="expression" dxfId="${x.style}" priority="${i+1}"><formula>${esc(x.formula)}</formula></cfRule></conditionalFormatting>`).join("");
   const headerRow=3;
   const lastCol=col(Math.max(...s.rows.map(r=>r.length)));
   const lastRow=s.rows.length;
   return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="${s.freeze||headerRow}" topLeftCell="A${(s.freeze||headerRow)+1}" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="19"/><cols>${cols}</cols><sheetData>${rows}</sheetData>${s.autoFilter?`<autoFilter ref="A${headerRow}:${lastCol}${lastRow}"/>`:""}${s.merges?.length?`<mergeCells count="${s.merges.length}">${s.merges.map(m=>`<mergeCell ref="${m}"/>`).join("")}</mergeCells>`:""}${cf}</worksheet>`;
 };
 const files=[{name:"[Content_Types].xml",data:contentTypes},{name:"_rels/.rels",data:rels},{name:"xl/workbook.xml",data:wb},{name:"xl/_rels/workbook.xml.rels",data:wbRels},{name:"xl/styles.xml",data:styles},...sheets.map((s,i)=>({name:`xl/worksheets/sheet${i+1}.xml`,data:sheetXml(s)}))];
 const blob=zip(files),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
